/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type Frequency = {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "twiceDaily";
    twiceDaily: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: null;
};
export interface Medication {
    id: string;
    endDate?: Time;
    dosage: string;
    name: string;
    notes: string;
    scheduledTimes: Array<Time>;
    frequency: Frequency;
    startDate: Time;
}
export interface DoseLog {
    status: DoseStatus;
    scheduledTime: Time;
    medicationId: string;
    timestamp: Time;
}
export enum DoseStatus {
    taken = "taken",
    skipped = "skipped",
    missed = "missed"
}
export interface backendInterface {
    addMedication(id: string, name: string, dosage: string, frequency: Frequency, scheduledTimes: Array<Time>, startDate: Time, endDate: Time | null, notes: string): Promise<void>;
    deleteMedication(id: string): Promise<void>;
    getDoseHistory(medicationId: string): Promise<Array<DoseLog>>;
    getMedication(medicationId: string): Promise<Medication>;
    listAllMedications(): Promise<Array<Medication>>;
    logDose(medicationId: string, scheduledTime: Time, status: DoseStatus): Promise<void>;
    updateMedication(id: string, name: string, dosage: string, frequency: Frequency, scheduledTimes: Array<Time>, startDate: Time, endDate: Time | null, notes: string): Promise<void>;
}
import type { DoseLog as _DoseLog, DoseStatus as _DoseStatus, Frequency as _Frequency, Medication as _Medication, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMedication(arg0: string, arg1: string, arg2: string, arg3: Frequency, arg4: Array<Time>, arg5: Time, arg6: Time | null, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedication(arg0, arg1, arg2, to_candid_Frequency_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedication(arg0, arg1, arg2, to_candid_Frequency_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async deleteMedication(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedication(arg0);
            return result;
        }
    }
    async getDoseHistory(arg0: string): Promise<Array<DoseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoseHistory(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoseHistory(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMedication(arg0: string): Promise<Medication> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedication(arg0);
                return from_candid_Medication_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedication(arg0);
            return from_candid_Medication_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllMedications(): Promise<Array<Medication>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllMedications();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllMedications();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async logDose(arg0: string, arg1: Time, arg2: DoseStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDose(arg0, arg1, to_candid_DoseStatus_n15(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDose(arg0, arg1, to_candid_DoseStatus_n15(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateMedication(arg0: string, arg1: string, arg2: string, arg3: Frequency, arg4: Array<Time>, arg5: Time, arg6: Time | null, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMedication(arg0, arg1, arg2, to_candid_Frequency_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMedication(arg0, arg1, arg2, to_candid_Frequency_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
}
function from_candid_DoseLog_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoseLog): DoseLog {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_DoseStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoseStatus): DoseStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Frequency_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Medication_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Medication): Medication {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: [] | [_Time];
    dosage: string;
    name: string;
    notes: string;
    scheduledTimes: Array<_Time>;
    frequency: _Frequency;
    startDate: _Time;
}): {
    id: string;
    endDate?: Time;
    dosage: string;
    name: string;
    notes: string;
    scheduledTimes: Array<Time>;
    frequency: Frequency;
    startDate: Time;
} {
    return {
        id: value.id,
        endDate: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.endDate)),
        dosage: value.dosage,
        name: value.name,
        notes: value.notes,
        scheduledTimes: value.scheduledTimes,
        frequency: from_candid_Frequency_n12(_uploadFile, _downloadFile, value.frequency),
        startDate: value.startDate
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _DoseStatus;
    scheduledTime: _Time;
    medicationId: string;
    timestamp: _Time;
}): {
    status: DoseStatus;
    scheduledTime: Time;
    medicationId: string;
    timestamp: Time;
} {
    return {
        status: from_candid_DoseStatus_n7(_uploadFile, _downloadFile, value.status),
        scheduledTime: value.scheduledTime,
        medicationId: value.medicationId,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: bigint;
} | {
    twiceDaily: null;
} | {
    daily: null;
} | {
    weekly: null;
}): {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "twiceDaily";
    twiceDaily: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: null;
} {
    return "custom" in value ? {
        __kind__: "custom",
        custom: value.custom
    } : "twiceDaily" in value ? {
        __kind__: "twiceDaily",
        twiceDaily: value.twiceDaily
    } : "daily" in value ? {
        __kind__: "daily",
        daily: value.daily
    } : "weekly" in value ? {
        __kind__: "weekly",
        weekly: value.weekly
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taken: null;
} | {
    skipped: null;
} | {
    missed: null;
}): DoseStatus {
    return "taken" in value ? DoseStatus.taken : "skipped" in value ? DoseStatus.skipped : "missed" in value ? DoseStatus.missed : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Medication>): Array<Medication> {
    return value.map((x)=>from_candid_Medication_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoseLog>): Array<DoseLog> {
    return value.map((x)=>from_candid_DoseLog_n5(_uploadFile, _downloadFile, x));
}
function to_candid_DoseStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseStatus): _DoseStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Frequency_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoseStatus): {
    taken: null;
} | {
    skipped: null;
} | {
    missed: null;
} {
    return value == DoseStatus.taken ? {
        taken: null
    } : value == DoseStatus.skipped ? {
        skipped: null
    } : value == DoseStatus.missed ? {
        missed: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: bigint;
} | {
    __kind__: "twiceDaily";
    twiceDaily: null;
} | {
    __kind__: "daily";
    daily: null;
} | {
    __kind__: "weekly";
    weekly: null;
}): {
    custom: bigint;
} | {
    twiceDaily: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value.__kind__ === "custom" ? {
        custom: value.custom
    } : value.__kind__ === "twiceDaily" ? {
        twiceDaily: value.twiceDaily
    } : value.__kind__ === "daily" ? {
        daily: value.daily
    } : value.__kind__ === "weekly" ? {
        weekly: value.weekly
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
