/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DoseLog {
  'status' : DoseStatus,
  'scheduledTime' : Time,
  'medicationId' : string,
  'timestamp' : Time,
}
export type DoseStatus = { 'taken' : null } |
  { 'skipped' : null } |
  { 'missed' : null };
export type Frequency = { 'custom' : bigint } |
  { 'twiceDaily' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface Medication {
  'id' : string,
  'endDate' : [] | [Time],
  'dosage' : string,
  'name' : string,
  'notes' : string,
  'scheduledTimes' : Array<Time>,
  'frequency' : Frequency,
  'startDate' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addMedication' : ActorMethod<
    [string, string, string, Frequency, Array<Time>, Time, [] | [Time], string],
    undefined
  >,
  'deleteMedication' : ActorMethod<[string], undefined>,
  'getDoseHistory' : ActorMethod<[string], Array<DoseLog>>,
  'getMedication' : ActorMethod<[string], Medication>,
  'listAllMedications' : ActorMethod<[], Array<Medication>>,
  'logDose' : ActorMethod<[string, Time, DoseStatus], undefined>,
  'updateMedication' : ActorMethod<
    [string, string, string, Frequency, Array<Time>, Time, [] | [Time], string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];