/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Frequency = IDL.Variant({
  'custom' : IDL.Nat,
  'twiceDaily' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Time = IDL.Int;
export const DoseStatus = IDL.Variant({
  'taken' : IDL.Null,
  'skipped' : IDL.Null,
  'missed' : IDL.Null,
});
export const DoseLog = IDL.Record({
  'status' : DoseStatus,
  'scheduledTime' : Time,
  'medicationId' : IDL.Text,
  'timestamp' : Time,
});
export const Medication = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'scheduledTimes' : IDL.Vec(Time),
  'frequency' : Frequency,
  'startDate' : Time,
});

export const idlService = IDL.Service({
  'addMedication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Frequency,
        IDL.Vec(Time),
        Time,
        IDL.Opt(Time),
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteMedication' : IDL.Func([IDL.Text], [], []),
  'getDoseHistory' : IDL.Func([IDL.Text], [IDL.Vec(DoseLog)], ['query']),
  'getMedication' : IDL.Func([IDL.Text], [Medication], ['query']),
  'listAllMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
  'logDose' : IDL.Func([IDL.Text, Time, DoseStatus], [], []),
  'updateMedication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Frequency,
        IDL.Vec(Time),
        Time,
        IDL.Opt(Time),
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Frequency = IDL.Variant({
    'custom' : IDL.Nat,
    'twiceDaily' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Time = IDL.Int;
  const DoseStatus = IDL.Variant({
    'taken' : IDL.Null,
    'skipped' : IDL.Null,
    'missed' : IDL.Null,
  });
  const DoseLog = IDL.Record({
    'status' : DoseStatus,
    'scheduledTime' : Time,
    'medicationId' : IDL.Text,
    'timestamp' : Time,
  });
  const Medication = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'scheduledTimes' : IDL.Vec(Time),
    'frequency' : Frequency,
    'startDate' : Time,
  });
  
  return IDL.Service({
    'addMedication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Frequency,
          IDL.Vec(Time),
          Time,
          IDL.Opt(Time),
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteMedication' : IDL.Func([IDL.Text], [], []),
    'getDoseHistory' : IDL.Func([IDL.Text], [IDL.Vec(DoseLog)], ['query']),
    'getMedication' : IDL.Func([IDL.Text], [Medication], ['query']),
    'listAllMedications' : IDL.Func([], [IDL.Vec(Medication)], ['query']),
    'logDose' : IDL.Func([IDL.Text, Time, DoseStatus], [], []),
    'updateMedication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Frequency,
          IDL.Vec(Time),
          Time,
          IDL.Opt(Time),
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };